PalantirLanguageServer#setSystemProperties
palantir/language-servers pull request #151
Opened 2016-12-12 00:36 UTC by ags799

Introduces a standard `setSystemProperties` method for language servers to call during their startup. They can call this method to set system properties per Palantir conventions.

2017-01-03 11:47 UTC, darora requested changes
I dislike this change because-

(1) relies on servers invoking this call manually (easily fixed by moving this to a constructor)
(2) hardcodes this and any other properties in a manner that makes changing them tantamount to jar surgery or having to deploy a new build (vs editing conf options for the gradle-java-dist)

2017-01-03 14:44 UTC, ags799 commented
@darora 2 ideas:

We could make the language server configuration more sophisticated. Eg

```yaml
type: mesa
supportedExtensions: [ ... ]
executionJar: service/language-servers/mesa-language-server.jar
executionArguments:
    ...
```

The `executionJar` would be an alternative to `executionCommand`. We would then be able to run the jar with whatever `-D` arguments we like.

Or could we just do this by running the regular old `executionCommand` with `JAVA_OPTS` set?

2017-01-03 14:49 UTC, gatesn commented
Why not allow setting `environment`, it's much more general, would allow things like PYTHONPATH as well as JAVA_OPTS and can be passed directly into execve when the worker fork+execs. 

Would be nice to also allow executionCommand to be passed as a list to prevent errors in shell escaping.

2017-01-03 15:00 UTC, ags799 commented
@ngates I think we want to have these `JAVA_OPTS` constant for all language servers, they wouldn't be specified in the worker configuration.

And +1 to the list idea, https://github.palantir.build/elements/code-assist/issues/577

2017-01-03 15:20 UTC, gatesn commented
It would be very limiting for every language server to have the same JAVA_OPTS. Also environment variables can be very useful for passing config such as DEBUG flags.

Regarding the command as a list, this also removes the need for executionArguments.

2017-01-03 15:42 UTC, ags799 commented
@gatesn agreed, we should allow language servers to define environment variables as they please. The problem we're trying to solve here is setting Java system properties as they are in gradle-java-distribution, the critical one being [`java.io.tmpdir`](https://github.palantir.build/elements/code-assist/pull/575).

2017-01-03 16:01 UTC, JiahuiJiang commented
Don't think it should be `executionJar` because some language servers (like Python) is not using Java to execute.
So I think have a worker level environment configuration (that will be added to every worker during their startup time) and change execution command into a list sounds good

2017-01-03 16:06 UTC, ags799 commented
Yeah we would either have `executionJar` or `executionCommand`, `executionJar` when possible. But agreed, if we can use `JAVA_OPTS` instead that's preferable.

2017-01-03 16:08 UTC, gatesn commented
So:

```
executionCommand: ["java", "-Djava.io.tmpdir=XXX", ...]
```

or 

```
executionCommand: ["java", ...]
environment:
  JAVA_OPTS: "-Djava.io.tmpdir=XXX"
```

2017-01-03 16:11 UTC, ags799 commented
The latter, but the JAVA_OPTS will by default have the tmpdir=var/tmp, and whatever other gradle-java-distribution properties we are missing and require. Perhaps it will be necessary to add these default settings to a configured JAVA_OPTS as you've described.

2017-01-04 22:12 UTC, gracew commented
closing this as I think the consensus is to keep this sort of thing configurable versus having to build a new language-servers jar.

actions tracked at: elements/code-assist#577, elements/code-assist#581

2017-01-04 22:12 UTC, closed without merging