Upgrade to Eclipse lsp4j
palantir/language-servers pull request #158
Opened 2017-06-20 15:21 UTC by darora

Fixes #150

2017-06-20 17:42 UTC, jiahuijiang requested changes
We can remove
"https://oss.sonatype.org/content/repositories/snapshots/" from build.gradle - allprojects.repositories now

2017-06-20 17:42 UTC, JiahuiJiang commented on groovy-language-server/src/main/java/com/palantir/ls/groovy/GroovyLanguageServer.java
> +            WorkspaceService workspaceService) {
nitpick: all on the 2nd line

2017-06-20 17:42 UTC, JiahuiJiang commented on groovy-language-server/src/main/java/com/palantir/ls/groovy/GroovyLanguageServer.java
>                  new GroovyLanguageServer(state, new DefaultTextDocumentService(state),
nitpick:
LanguageServer server = new GroovyLanguageServer(
    state, new DefaultTextDocumentService(state), new DefaultWorkspaceService(state));

2017-06-20 17:42 UTC, JiahuiJiang commented on groovy-language-server/src/main/java/com/palantir/ls/groovy/GroovyLanguageServer.java
> +    }
also set showMessage, showMessageRequest and logMessage

2017-06-20 17:42 UTC, JiahuiJiang commented on groovy-language-server/src/main/java/com/palantir/ls/groovy/GroovyWorkspaceCompiler.java
> +            checkNotNull(message1, "message cannot be null");
if it's null, convert it into empty? because groovy's warningMessage;s message is nullable

2017-06-20 17:42 UTC, JiahuiJiang commented on groovy-language-server/src/main/java/com/palantir/ls/groovy/GroovyWorkspaceCompiler.java
> +            diagnosticsByFile.compute(workspaceRoot.toUri(),
diagnosticsByFile.computeIfAbsent(workspaceRoot.toUri(), (key) -> List.newArrayList())
    .add(diaf)?

2017-06-20 17:42 UTC, JiahuiJiang commented on groovy-language-server/src/main/java/com/palantir/ls/groovy/GroovyWorkspaceCompiler.java
> +                checkNotNull(message1, "message cannot be null");
same convert message

2017-06-20 17:42 UTC, JiahuiJiang commented on groovy-language-server/src/main/java/com/palantir/ls/groovy/GroovyWorkspaceCompiler.java
> +            diagnosticsByFile.compute(uri, (key, existingValue) -> {
same computeIfAbsent to add empty list, then add "diagnostic"

2017-06-20 17:42 UTC, JiahuiJiang commented on groovy-language-server/src/main/java/com/palantir/ls/groovy/MethodVisitor.java
> +        String containerName;
make these final or create a "new SymbolInformation()" first then set each property below

2017-06-20 17:42 UTC, JiahuiJiang commented on groovy-language-server/src/test/java/com/palantir/ls/groovy/GroovyLanguageServerIntegrationTest.java
> +        while (server != null && counter++ < 20) {
when will this server be set to null?

2017-06-20 17:42 UTC, JiahuiJiang commented on groovy-language-server/src/test/java/com/palantir/ls/groovy/GroovyWorkspaceCompilerTest.java
> +                                new Diagnostic(Ranges.createRange(0, 19, 0, 26),
newline for the 1st arg

2017-06-20 17:42 UTC, JiahuiJiang commented on language-server-commons/src/main/java/com/palantir/ls/services/AbstractTextDocumentService.java
> +    public CompletableFuture<Either<List<CompletionItem>, CompletionList>> completion(
woooooooow

2017-06-20 17:42 UTC, JiahuiJiang commented on language-server-commons/src/test/java/com/palantir/ls/services/DefaultTextDocumentServiceTest.java
> +                false,
nitpick: same line?

2017-06-20 17:42 UTC, JiahuiJiang commented on groovy-language-server/src/test/java/com/palantir/ls/groovy/GroovyLanguageServerIntegrationTest.java
> +            actualServer = new GroovyLanguageServer(
make arguments on the same line for these two constructors? no strong opinion

2017-06-20 17:42 UTC, JiahuiJiang commented on language-server-commons/src/main/java/com/palantir/ls/util/LoggerMessageTracer.java
> -public class LoggerMessageTracer implements MessageTracer {
I think we still want to implement this. Right now all the requests/responses will be logged in language server logs. But right now it only logs errors https://github.com/eclipse/lsp4j/blob/bd1a4ddf97ea3a0ee9031ade9b10410bfb093999/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/json/StreamMessageProducer.java#L109

We should implement streamMessageProducer and streamMessageConsumer again
https://github.com/eclipse/lsp4j/issues/23

2017-06-20 17:59 UTC, darora commented on groovy-language-server/src/main/java/com/palantir/ls/groovy/GroovyWorkspaceCompiler.java
> +                checkNotNull(message1, "message cannot be null");
hmm I don't think the result of the `toString()` would be null?

2017-06-20 18:00 UTC, JiahuiJiang commented on groovy-language-server/src/main/java/com/palantir/ls/groovy/GroovyWorkspaceCompiler.java
> +                checkNotNull(message1, "message cannot be null");
ohhh oops, nvm thought this is the same as the above

2017-06-20 19:40 UTC, darora commented on groovy-language-server/src/test/java/com/palantir/ls/groovy/GroovyLanguageServerIntegrationTest.java
> +        while (server != null && counter++ < 20) {
if the other thread hasn't been scheduled for long enough

2017-06-20 19:43 UTC, darora commented
@JiahuiJiang think I addressed all your comments. Added a DelegatingOutputStream that hooks into the existing LSPLauncher methods, rather than implementing our own subclass of the Consumer/Producer

2017-06-20 19:59 UTC, jiahuijiang approved these changes
small nit-picks and one question in delegateOutputStream

2017-06-20 19:59 UTC, JiahuiJiang commented on groovy-language-server/src/main/java/com/palantir/ls/groovy/GroovyTreeParser.java
> +        SymbolKind kind;
final here too

2017-06-20 19:59 UTC, JiahuiJiang commented on language-server-commons/src/main/java/com/palantir/ls/services/AbstractTextDocumentService.java
> +//    @Override
remove?

2017-06-20 19:59 UTC, JiahuiJiang commented on language-server-commons/src/main/java/com/palantir/ls/util/CompletionUtils.java
> +            CompletionItem completionItem = new CompletionItem(symbol.getName());
symbols.stream.map(****).collect()

2017-06-20 19:59 UTC, JiahuiJiang commented on language-server-commons/src/main/java/com/palantir/ls/util/DelegatingOutputStream.java
> +        closed = true;
do we need to flush first before closing? or is it already taken cared of?

2017-06-21 13:19 UTC, darora commented on language-server-commons/src/main/java/com/palantir/ls/util/DelegatingOutputStream.java
> +        closed = true;
Not really something demanded by the OutputStream interface, but does seem to be more of a convention. Added.

2017-06-21 14:25 UTC, merged